import React from "react";
import { ShieldCheck, Lock, Eye, Save } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen pb-12 font-sans text-[#3A4D39] overflow-x-hidden">
      {/* header */}
      <header className="pt-30 pb-32 px-10 text-center text-white relative">
        <div className="max-w-4xl mx-auto space-y-6">
          <div className="flex justify-center mb-6">
            <div className="bg-[#3A4D39]/10 p-4 rounded-full backdrop-blur-sm shadow-inner border border-white/20">
              <ShieldCheck className="w-10 h-10 text-[#3A4D39]" />
            </div>
          </div>
          <h1 className="text-4xl md:text-6xl font-black tracking-tight drop-shadow-sm text-[#4F6F52]">
            Privacy Policy
          </h1>
          <p className=" text-lg md:text-xl font-medium max-w-2xl mx-auto leading-relaxed text-[#4F6F52]/60">
            NutriBin: Protecting Your Data and Privacy
          </p>
        </div>
      </header>

      {/* main container */}
      <main className="max-w-6xl mx-auto -mt-24 px-4 sm:px-6 relative z-10">
        <div className="bg-white shadow-2xl border-none overflow-hidden rounded-2xl">
          <div className="p-8 md:p-16 space-y-16">
            {/* intro */}
            <div className="space-y-6 border-b pb-10 border-[#ECE3CE]">
              <div className="flex items-center justify-between flex-wrap gap-4">
                <p className="text-sm font-bold tracking-wide text-[#4F6F52] uppercase bg-[#4F6F52]/10 px-3 py-1 rounded-full">
                  Effective Date: January 2026
                </p>
                <div className="text-xs text-[#739072] font-mono">
                  REF: NB-PP-V1
                </div>
              </div>
              <p className="text-lg leading-relaxed text-[#4F6F52]">
                Your privacy is important to us. This Privacy Policy explains
                how NutriBin collects, uses, and safeguards your information
                when you use our system.
              </p>
            </div>

            {/* timeline section */}
            <div className="relative">
              {/* timeline vertical line */}
              <div className="hidden md:block absolute left-9.75 top-4 bottom-4 w-0.5 bg-[#ECE3CE] -z-10" />

              <div className="space-y-16">
                {/* section 1 */}
                <PolicySection number="1" title="Information We Collect">
                  <p>
                    We collect information that you provide directly to us, such
                    as when you create an account, as well as data generated by
                    the NutriBin system during operation.
                  </p>
                  <div className="grid md:grid-cols-2 gap-4 mt-6">
                    <div className="bg-[#FAF9F6] p-5 rounded-xl border border-[#ECE3CE]">
                      <div className="flex items-center gap-3 mb-3">
                        <Lock className="w-5 h-5 text-[#3A4D39]" />
                        <strong className="text-[#3A4D39]">Account Data</strong>
                      </div>
                      <span className="text-sm text-[#739072]">
                        Email address, password (encrypted), and optional
                        profile information.
                      </span>
                    </div>
                    <div className="bg-[#FAF9F6] p-5 rounded-xl border border-[#ECE3CE]">
                      <div className="flex items-center gap-3 mb-3">
                        <Save className="w-5 h-5 text-[#3A4D39]" />
                        <strong className="text-[#3A4D39]">System Data</strong>
                      </div>
                      <span className="text-sm text-[#739072]">
                        Sensor readings (pH, Moisture, Temperature,
                        Ammonia/H2S), composting logs, and machine status.
                      </span>
                    </div>
                  </div>
                </PolicySection>

                {/* section 2 */}
                <PolicySection number="2" title="How We Use Your Information">
                  <p className="mb-4">
                    The collected information is used for the following
                    purposes:
                  </p>
                  <ul className="grid md:grid-cols-2 gap-3">
                    {[
                      "Providing real-time monitoring and analytics",
                      "Sending system alerts and notifications",
                      "Improving system performance and calibration",
                      "Ensuring the security of your account",
                      "Generating fertilizer readiness reports",
                    ].map((item, idx) => (
                      <li
                        key={idx}
                        className="flex items-start gap-3 text-[#4F6F52] bg-[#FAF9F6] p-3 rounded-lg border border-[#ECE3CE]"
                      >
                        <span className="h-1.5 w-1.5 rounded-full bg-[#3A4D39] mt-2 shrink-0" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </PolicySection>

                {/* section 3 */}
                <PolicySection number="3" title="Data Security">
                  <p>
                    We implement industry-standard security measures to protect
                    your data. All sensitive information, including passwords
                    and communication with the hardware system, is encrypted
                    using modern protocols.
                  </p>
                  <div className="mt-4 p-4 bg-[#ECE3CE]/30 rounded-lg border-l-4 border-[#3A4D39] text-[#4F6F52]">
                    <strong>Note:</strong> While we strive to protect your data,
                    no method of transmission over the internet is 100% secure.
                  </div>
                </PolicySection>

                {/* section 4 */}
                <PolicySection number="4" title="Your Rights">
                  <p>
                    You have the right to access, update, or delete your
                    personal information at any time through your account
                    settings. If you wish to close your account or have your
                    data removed from our systems, please contact support.
                  </p>
                </PolicySection>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* copyright footer */}
      <footer className="text-center text-[#739072] text-sm mt-12 pb-8 font-medium">
        &copy; 2026 NutriBin System. All rights reserved.
      </footer>
    </div>
  );
}

// --- Helper Component for Timeline Sections ---
function PolicySection({ number, title, children }) {
  return (
    <div className="relative flex flex-col md:flex-row gap-6 md:gap-12 group">
      {/* number bubble */}
      <div className="shrink-0">
        <div className="flex items-center justify-center w-16 h-16 md:w-20 md:h-20 rounded-full bg-[#3A4D39] group-hover:bg-[#4F6F52] transition-colors duration-300 text-[#ECE3CE] text-2xl md:text-3xl font-black shadow-lg ring-8 ring-white z-10 relative">
          {number}
        </div>
      </div>

      {/* content */}
      <div className="flex-1 pt-2 md:pt-4">
        <h2 className="text-2xl md:text-3xl font-bold mb-6 text-[#3A4D39] group-hover:text-[#4F6F52] transition-colors">
          {title}
        </h2>
        <div className="text-[#4F6F52] leading-relaxed text-lg space-y-4">
          {children}
        </div>
      </div>
    </div>
  );
}
